### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by fpesari** [stefets/flaskdings#20]
Hello Stéphane,

nice program! What about adding a LICENSE file to make the license explicit and maybe, if it's FLOSS, attract contributors and packagers? Thank you!

**Comment by stefets** [comment]
Hello @fpesari !

Sorry for the late! I never saw your issue.

I have no objection of adding a licence. I don't know much about which one to use. I will dig on that, if you have suggestion you are welcome!

**Comment by fpesari** [comment]
Hello,

thank you for your reply :smiley: OK, let me give you a very wide and quick overview of licenses. Simplifying, there are two kinds of free and open source licenses:

1. Copyleft - These licenses require that everyone which makes derivative works of your program shares their modifications under the same license. The most important copyleft licenses are the GPLv2 (used by Linux, mididings), GPLv3 (used by Ardour, GIMP) and AGPLv3 (designed for web apps, used by NextCloud, Mastodon)
2. Permissive - These licenses usually only require that everybody which makes derivative works of your program credits you as the original author, with no requirement of releasing modifications. There are many permissive licenses which are very similar, the most famous are MIT (used by Node.js), BSD (used by Flask) and Apache 2.0 (used by TypeScript).

My suggestion is to use the GPLv3 or any later version ([full text](https://www.gnu.org/licenses/gpl-3.0.txt)). This is because it's compatible with the license mididings used (GPLv2 or any later version) and you interfaced with it.

If you want, I can make a pull request to properly set up the GPLv3+. Else, you can just put the full text into a file called `LICENSE`.

**Comment by stefets** [comment]
Ok! It would be nice if you can help me and PR the changes for setting up the LICENSE; I assigned you to the issue :)

There is a very new community fork of mididings and the maintainer has rearrange the licences.

https://github.com/mididings/mididings/tree/primary/LICENSES



Thanks!

**Comment by fpesari** [comment]
> Ok! It would be nice if you can help me and PR the changes for setting up the LICENSE; I assigned you to the issue :)
> 
> There is a very new community fork of mididings and the maintainer has rearrange the licences.
> 
> https://github.com/mididings/mididings/tree/primary/LICENSES
> 
> Thanks!

Thanks for the link! It's because mididings has extensive documentation and they decided to release it under a license suited for documentation, the GDFL-1.3 or later. I think that for flaskdings, for now it's not necessary to do the same. I will soon open a PR with all needed changes.

Also, as a side note, mididings is released under the GPLv2 with an "or any later version" clause, which makes it compatible with the GPLv3. I would normally use only the GPLv3 or AGPLv3 but for the sake of consistency, I will make a PR for using the GPLv2 with an "any later version" too, which in the future can be easily switched to the GPLv3, if necessary.
